package org.softgauges_behaviors;

public enum BehaviorType {
    // Social — positive
    HELPED_PLAYER, GAVE_ITEM, SAVED_PLAYER, IGNORED_HELP_REQUEST,

    // Leadership
    GAVE_INSTRUCTION, INITIATED_GROUP_TASK, DIVIDED_TASKS, FOLLOWED_PLAYER,

    // Problem solving
    SELF_CORRECTED_BUILD, ASKED_FOR_HELP, REPEATED_MISTAKE, // Removed EXPLORED_NEW_AREA

    // Combat (New)
    DEFEATED_MONSTER, KILLED_VILLAGER,

    // Emotional regulation
    RAGE_QUIT, AGGRESSIVE_CHAT, CALM_RECOVERY, POSITIVE_EXPRESSION,

    // Communication
    SENT_ENCOURAGEMENT, SILENT_PERIOD, DIRECTED_MESSAGE, ASKED_QUESTION,

    // Aggression & Harassment (negative)
    KILLED_FRIENDLY_PLAYER, HARASSED_PLAYER,

    // Griefing & Malice (negative)
    GRIEFED_STRUCTURE, STOLE_FROM_CONTAINER,
    PLACED_TNT_NEAR_STRUCTURE, STARTED_FIRE_IN_BUILD,
    PLACED_LAVA_DESTRUCTIVELY, KILLED_TAMED_ANIMAL,

    // Resource Management
    COLLECTED_ITEM, DISCARDED_ITEM,

    // Session Summaries
    SESSION_CHAT_HISTORY
}
